// Private document storage behind a small driver interface so business logic
// only ever handles opaque storage keys. To move to Hetzner Object Storage
// (S3-compatible), add an `s3` driver with the same four methods and set
// STORAGE_DRIVER=s3 — nothing else needs to change.
const fs = require('fs/promises');
const path = require('path');
const crypto = require('crypto');
const env = require('../../config/env');

const EXTENSIONS = { 'application/pdf': 'pdf', 'image/png': 'png', 'image/jpeg': 'jpg' };

function localDriver(rootDir) {
  const resolveKey = (key) => {
    const full = path.resolve(rootDir, key);
    // Keys are generated by us, but never let one escape the storage root.
    if (!full.startsWith(path.resolve(rootDir) + path.sep)) throw new Error('Invalid storage key');
    return full;
  };
  return {
    async put(buffer, { prefix, mimeType }) {
      const key = `${prefix}/${crypto.randomUUID()}.${EXTENSIONS[mimeType] || 'bin'}`;
      const full = resolveKey(key);
      await fs.mkdir(path.dirname(full), { recursive: true });
      await fs.writeFile(full, buffer, { flag: 'wx' });
      return key;
    },
    async get(key) {
      return fs.readFile(resolveKey(key));
    },
    async remove(key) {
      await fs.rm(resolveKey(key), { force: true });
    },
    async exists(key) {
      try {
        await fs.access(resolveKey(key));
        return true;
      } catch {
        return false;
      }
    },
  };
}

const drivers = {
  local: () => localDriver(env.storage.localDir),
};

if (!drivers[env.storage.driver]) {
  throw new Error(`Unknown STORAGE_DRIVER "${env.storage.driver}". Available: ${Object.keys(drivers).join(', ')}`);
}

module.exports = drivers[env.storage.driver]();
